# PLEASE NOTE: Please run this notebook OUTSIDE a Spark notebook as it should run in a plain Default Python 3.6 Free Environment

This is the last assignment for the Coursera course "Advanced Machine Learning and Signal Processing"

Just execute all cells one after the other and you are done - just note that in the last one you should update your email address (the one you've used for coursera) and obtain a submission token, you get this from the programming assignment directly on coursera.

Please fill in the sections labelled with "###YOUR_CODE_GOES_HERE###"

The purpose of this assignment is to learn how feature engineering boosts model performance. You will apply Discrete Fourier Transformation on the accelerometer sensor time series and therefore transforming the dataset from the time to the frequency domain. 

After that, you’ll use a classification algorithm of your choice to create a model and submit the new predictions to the grader. Done.

In [1]:
from IPython.display import Markdown, display
def printmd(string):
    display(Markdown('# <span style="color:red">'+string+'</span>'))


if ('sc' in locals() or 'sc' in globals()):
    printmd('<<<<<!!!!! It seems that you are running in a IBM Watson Studio Apache Spark Notebook. Please run it in an IBM Watson Studio Default Runtime (without Apache Spark) !!!!!>>>>>')

# <span style="color:red"><<<<<!!!!! It seems that you are running in a IBM Watson Studio Apache Spark Notebook. Please run it in an IBM Watson Studio Default Runtime (without Apache Spark) !!!!!>>>>></span>

In [ ]:
!pip install pyspark==2.4.5

In [ ]:
!pip install https://github.com/IBM/coursera/blob/master/systemml-1.3.0-SNAPSHOT-python.tar.gz?raw=true

In [1]:
from pyspark import SparkContext, SparkConf
from pyspark.sql import SQLContext, SparkSession
from pyspark.sql.types import StructType, StructField, DoubleType, IntegerType, StringType
sc = SparkContext.getOrCreate(SparkConf().setMaster("local[*]"))
from pyspark.sql import SparkSession
spark = SparkSession \
    .builder \
    .getOrCreate()


So the first thing we need to ensure is that we are on the latest version of SystemML, which is 1.3.0 (as of 20th March'19) Please use the code block below to check if you are already on 1.3.0 or higher. 1.3 contains a necessary fix, that's we are running against the SNAPSHOT

In [3]:
!mkdir -p /home/daniel/work/systemml

In [2]:
from systemml import MLContext, dml
ml = MLContext(spark)
ml.setConfigProperty("sysml.localtmpdir", "mkdir /home/daniel/work/systemml")
print(ml.version())
    
if not ml.version() == '1.3.0-SNAPSHOT':
    raise ValueError('please upgrade to SystemML 1.3.0, or restart your Kernel (Kernel->Restart & Clear Output)')

1.3.0-SNAPSHOT

In [5]:
!wget https://github.com/IBM/coursera/blob/master/coursera_ml/shake.parquet?raw=true
!mv shake.parquet?raw=true shake.parquet

--2020-07-18 15:19:36--  https://github.com/IBM/coursera/blob/master/coursera_ml/shake.parquet?raw=true
Resolving github.com (github.com)... 140.82.118.3
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/IBM/skillsnetwork/blob/master/coursera_ml/shake.parquet?raw=true [following]
--2020-07-18 15:19:36--  https://github.com/IBM/skillsnetwork/blob/master/coursera_ml/shake.parquet?raw=true
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/IBM/skillsnetwork/raw/master/coursera_ml/shake.parquet [following]
--2020-07-18 15:19:36--  https://github.com/IBM/skillsnetwork/raw/master/coursera_ml/shake.parquet
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/IBM/skillsnetwork/master/coursera_ml/shake.parquet [following]
--2020-07-18 15:19:36--  https://raw.githubusercontent.com/IBM/skillsnetwork/master/coursera_ml/shake.parquet
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.120.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.120.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 74727 (73K) [application/octet-stream]
Saving to: ‘shake.parquet?raw=true’

shake.parquet?raw=t 100%[===================>]  72.98K  --.-KB/s    in 0.05s

2020-07-18 15:19:37 (1.33 MB/s) - ‘shake.parquet?raw=true’ saved [74727/74727]

Now it’s time to read the sensor data and create a temporary query table.

In [3]:
df=spark.read.parquet('shake.parquet')

In [4]:
df.show()

+-----+---------+-----+-----+-----+
|CLASS| SENSORID|    X|    Y|    Z|
+-----+---------+-----+-----+-----+
|    2| qqqqqqqq| 0.12| 0.12| 0.12|
|    2|aUniqueID| 0.03| 0.03| 0.03|
|    2| qqqqqqqq|-3.84|-3.84|-3.84|
|    2| 12345678| -0.1| -0.1| -0.1|
|    2| 12345678|-0.15|-0.15|-0.15|
|    2| 12345678| 0.47| 0.47| 0.47|
|    2| 12345678|-0.06|-0.06|-0.06|
|    2| 12345678|-0.09|-0.09|-0.09|
|    2| 12345678| 0.21| 0.21| 0.21|
|    2| 12345678|-0.08|-0.08|-0.08|
|    2| 12345678| 0.44| 0.44| 0.44|
|    2|    gholi| 0.76| 0.76| 0.76|
|    2|    gholi| 1.62| 1.62| 1.62|
|    2|    gholi| 5.81| 5.81| 5.81|
|    2| bcbcbcbc| 0.58| 0.58| 0.58|
|    2| bcbcbcbc|-8.24|-8.24|-8.24|
|    2| bcbcbcbc|-0.45|-0.45|-0.45|
|    2| bcbcbcbc| 1.03| 1.03| 1.03|
|    2|aUniqueID|-0.05|-0.05|-0.05|
|    2| qqqqqqqq|-0.44|-0.44|-0.44|
+-----+---------+-----+-----+-----+
only showing top 20 rows

In [8]:
!pip install pixiedust

Collecting pixiedust
  Downloading pixiedust-1.1.18.tar.gz (197 kB)
     |████████████████████████████████| 197 kB 1.5 MB/s eta 0:00:01
Collecting mpld3
  Downloading mpld3-0.5.1.tar.gz (1.0 MB)
     |████████████████████████████████| 1.0 MB 1.7 MB/s eta 0:00:01
Requirement already satisfied: lxml in /home/daniel/anaconda3/lib/python3.7/site-packages (from pixiedust) (4.5.1)
Collecting geojson
  Downloading geojson-2.5.0-py2.py3-none-any.whl (14 kB)
Collecting astunparse
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting markdown
  Downloading Markdown-3.2.2-py3-none-any.whl (88 kB)
     |████████████████████████████████| 88 kB 1.4 MB/s eta 0:00:01
Collecting colour
  Downloading colour-0.1.5-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: requests in /home/daniel/anaconda3/lib/python3.7/site-packages (from pixiedust) (2.24.0)
Requirement already satisfied: jinja2 in /home/daniel/anaconda3/lib/python3.7/site-packages (from mpld3->pixiedust) (2.11.2)
Requirement already satisfied: matplotlib in /home/daniel/anaconda3/lib/python3.7/site-packages (from mpld3->pixiedust) (3.2.2)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /home/daniel/anaconda3/lib/python3.7/site-packages (from astunparse->pixiedust) (0.34.2)
Requirement already satisfied: six<2.0,>=1.6.1 in /home/daniel/anaconda3/lib/python3.7/site-packages (from astunparse->pixiedust) (1.15.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /home/daniel/anaconda3/lib/python3.7/site-packages (from markdown->pixiedust) (1.6.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/daniel/anaconda3/lib/python3.7/site-packages (from requests->pixiedust) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /home/daniel/anaconda3/lib/python3.7/site-packages (from requests->pixiedust) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/daniel/anaconda3/lib/python3.7/site-packages (from requests->pixiedust) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/daniel/anaconda3/lib/python3.7/site-packages (from requests->pixiedust) (3.0.4)
Requirement already satisfied: MarkupSafe>=0.23 in /home/daniel/anaconda3/lib/python3.7/site-packages (from jinja2->mpld3->pixiedust) (1.1.1)
Requirement already satisfied: numpy>=1.11 in /home/daniel/anaconda3/lib/python3.7/site-packages (from matplotlib->mpld3->pixiedust) (1.18.5)
Requirement already satisfied: python-dateutil>=2.1 in /home/daniel/anaconda3/lib/python3.7/site-packages (from matplotlib->mpld3->pixiedust) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/daniel/anaconda3/lib/python3.7/site-packages (from matplotlib->mpld3->pixiedust) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/daniel/anaconda3/lib/python3.7/site-packages (from matplotlib->mpld3->pixiedust) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /home/daniel/anaconda3/lib/python3.7/site-packages (from matplotlib->mpld3->pixiedust) (0.10.0)
Requirement already satisfied: zipp>=0.5 in /home/daniel/anaconda3/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->markdown->pixiedust) (3.1.0)
Building wheels for collected packages: pixiedust, mpld3
  Building wheel for pixiedust (setup.py) ... done
  Created wheel for pixiedust: filename=pixiedust-1.1.18-py3-none-any.whl size=321728 sha256=c919611dad65608afbf4080c54f16ea5642165a0e05d85d773ea304d01b949cd
  Stored in directory: /home/daniel/.cache/pip/wheels/41/4c/20/08a843440aaeffc976c1848c9eb44be6ec68dcd964421ec6f7
  Building wheel for mpld3 (setup.py) ... done
  Created wheel for mpld3: filename=mpld3-0.5.1-py3-none-any.whl size=364062 sha256=e1fc235abdab7fa5e000a4f3830647799d6117b541df1ae5d1b5dad99c686740
  Stored in directory: /home/daniel/.cache/pip/wheels/b9/36/27/d61b9f1327012961fa31f05a20b190f836dd3fcb1c0264177b
Successfully built pixiedust mpld3
Installing collected packages: mpld3, geojson, astunparse, markdown, colour, pixiedust
Successfully installed astunparse-1.6.3 colour-0.1.5 geojson-2.5.0 markdown-3.2.2 mpld3-0.5.1 pixiedust-1.1.18

In [ ]:
import pixiedust
display(df)

In [7]:
df.createOrReplaceTempView("df")

We’ll use Apache SystemML to implement Discrete Fourier Transformation. This way all computation continues to happen on the Apache Spark cluster for advanced scalability and performance.

As you’ve learned from the lecture, implementing Discrete Fourier Transformation in a linear algebra programming language is simple. Apache SystemML DML is such a language and as you can see the implementation is straightforward and doesn’t differ too much from the mathematical definition (Just note that the sum operator has been swapped with a vector dot product using the %*% syntax borrowed from R
):

<img style="float: left;" src="https://wikimedia.org/api/rest_v1/media/math/render/svg/1af0a78dc50bbf118ab6bd4c4dcc3c4ff8502223">

In [8]:
dml_script = '''
PI = 3.141592654
N = nrow(signal)

n = seq(0, N-1, 1)
k = seq(0, N-1, 1)

M = (n %*% t(k))*(2*PI/N)

Xa = cos(M) %*% signal
Xb = sin(M) %*% signal

DFT = cbind(Xa, Xb)
'''

Now it’s time to create a function which takes a single row Apache Spark data frame as argument (the one containing the accelerometer measurement time series for one axis) and returns the Fourier transformation of it. In addition, we are adding an index column for later joining all axis together and renaming the columns to appropriate names. The result of this function is an Apache Spark DataFrame containing the Fourier Transformation of its input in two columns.

In [9]:
from pyspark.sql.functions import monotonically_increasing_id

def dft_systemml(signal,name):
    prog = dml(dml_script).input('signal', signal).output('DFT')
    
    return (

    #execute the script inside the SystemML engine running on top of Apache Spark
    ml.execute(prog) 
     
         #read result from SystemML execution back as SystemML Matrix
        .get('DFT') 
     
         #convert SystemML Matrix to ApacheSpark DataFrame 
        .toDF() 
     
         #rename default column names
        .selectExpr('C1 as %sa' % (name), 'C2 as %sb' % (name)) 
     
         #add unique ID per row for later joining
        .withColumn("id", monotonically_increasing_id())
    )

Now it’s time to create individual DataFrames containing only a subset of the data. We filter simultaneously for accelerometer each sensor axis and one for each class. This means you’ll get 6 DataFrames. Please implement this using the relational API of DataFrames or SparkSQL. Please use class 1 and 2 and not 0 and 1. <h1><span style="color:red">Please make sure that each DataFrame has only ONE colum (only the measurement, eg. not CLASS column)</span></h1>

In [10]:
x0 = spark.sql("SELECT X FROM df WHERE CLASS=0")
y0 = spark.sql("SELECT Y FROM df WHERE CLASS=0")
z0 = spark.sql("SELECT Z FROM df WHERE CLASS=0")
x1 = spark.sql("SELECT X FROM df WHERE CLASS=1")
y1 = spark.sql("SELECT Y FROM df WHERE CLASS=1")
z1 = spark.sql("SELECT Z FROM df WHERE CLASS=1")

Since we’ve created this cool DFT function before, we can just call it for each of the 6 DataFrames now. And since the result of this function call is a DataFrame again we can use the pyspark best practice in simply calling methods on it sequentially. So what we are doing is the following:

- Calling DFT for each class and accelerometer sensor axis.
- Joining them together on the ID column. 
- Re-adding a column containing the class index.
- Stacking both Dataframes for each classes together

In [11]:
from pyspark.sql.functions import lit

df_class_0 = dft_systemml(x0,'x') \
    .join(dft_systemml(y0,'y'), on=['id'], how='inner') \
    .join(dft_systemml(z0,'z'), on=['id'], how='inner') \
    .withColumn('class', lit(0))
    
df_class_1 = dft_systemml(x1,'x') \
    .join(dft_systemml(y1,'y'), on=['id'], how='inner') \
    .join(dft_systemml(z1,'z'), on=['id'], how='inner') \
    .withColumn('class', lit(1))

df_dft = df_class_0.union(df_class_1)

df_dft.show()

SystemML Statistics:
Total execution time:		0.044 sec.
Number of executed Spark inst:	0.


SystemML Statistics:
Total execution time:		0.001 sec.
Number of executed Spark inst:	0.


SystemML Statistics:
Total execution time:		0.000 sec.
Number of executed Spark inst:	0.


SystemML Statistics:
Total execution time:		0.229 sec.
Number of executed Spark inst:	0.


SystemML Statistics:
Total execution time:		0.105 sec.
Number of executed Spark inst:	0.


SystemML Statistics:
Total execution time:		0.080 sec.
Number of executed Spark inst:	0.


+-----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----+
|         id|                  xa|                  xb|                  ya|                  yb|                  za|                  zb|class|
+-----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----+
| 8589934592|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|    0|
|          0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|    0|
| 8589934593|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|    0|
|17179869186|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|    0|
|          1|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|    0|
|17179869185|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|    0|
|17179869187|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|    0|
| 8589934594|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|    0|
| 8589934595|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|    0|
|25769803776|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|    0|
|          2|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|    0|
|25769803777|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|    0|
|17179869184|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|    0|
|25769803778|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|                 0.0|    0|
|         26| 0.05842761397588824|-0.01175613530955...| 0.05842761397588824|-0.01175613530955...| 0.05842761397588824|-0.01175613530955...|    1|
|17179869191|-0.10895275079055323|-0.04017484023996344|-0.10895275079055323|-0.04017484023996344|-0.10895275079055323|-0.04017484023996344|    1|
| 8589934592| 0.02589077121123453|0.024145789283483897| 0.02589077121123453|0.024145789283483897| 0.02589077121123453|0.024145789283483897|    1|
|         19| 0.07600499297235766|-0.04165706301892977| 0.07600499297235766|-0.04165706301892977| 0.07600499297235766|-0.04165706301892977|    1|
|          0|-0.05120371300320002|0.015844251463831505|-0.05120371300320002|0.015844251463831505|-0.05120371300320002|0.015844251463831505|    1|
|17179869201| 0.03912775214058598|-0.09049016952668232| 0.03912775214058598|-0.09049016952668232| 0.03912775214058598|-0.09049016952668232|    1|
+-----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----+
only showing top 20 rows

Please create a VectorAssembler which consumes the newly created DFT columns and produces a column “features”

In [13]:
from pyspark.ml.feature import VectorAssembler

In [14]:
vectorAssembler =  VectorAssembler(
    inputCols=["xa", "xb", "ya", "yb", "za", "zb"],
    outputCol="features")

Please insatiate a classifier from the SparkML package and assign it to the classifier variable. Make sure to set the “class” column as target.

In [15]:
from pyspark.ml.classification import GBTClassifier

In [16]:
classifier = GBTClassifier(labelCol="class", featuresCol="features", maxIter=10)

Let’s train and evaluate…

In [17]:
from pyspark.ml import Pipeline
pipeline = Pipeline(stages=[vectorAssembler, classifier])

In [ ]:
model = pipeline.fit(df_dft)

In [ ]:
prediction = model.transform(df_dft)

In [ ]:
prediction.show()

In [ ]:
from pyspark.ml.evaluation import MulticlassClassificationEvaluator
binEval = MulticlassClassificationEvaluator().setMetricName("accuracy") .setPredictionCol("prediction").setLabelCol("class")
    
binEval.evaluate(prediction)

If you are happy with the result (I’m happy with > 0.8) please submit your solution to the grader by executing the following cells, please don’t forget to obtain an assignment submission token (secret) from the Courera’s graders web page and paste it to the “secret” variable below, including your email address you’ve used for Coursera.

In [ ]:
!rm -Rf a2_m4.json

In [ ]:
prediction = prediction.repartition(1)
prediction.write.json('a2_m4.json')

In [ ]:
!rm -f rklib.py
!wget wget https://raw.githubusercontent.com/IBM/coursera/master/rklib.py

In [ ]:
from rklib import zipit
zipit('a2_m4.json.zip','a2_m4.json')

In [ ]:
!base64 a2_m4.json.zip > a2_m4.json.zip.base64

In [ ]:
from rklib import submit
key = "-fBiYHYDEeiR4QqiFhAvkA"
part = "IjtJk"
email = ###YOUR_CODE_GOES_HERE###
submission_token = ###YOUR_CODE_GOES_HERE### # (have a look here if you need more information on how to obtain the token https://youtu.be/GcDo0Rwe06U?t=276)

with open('a2_m4.json.zip.base64', 'r') as myfile:
    data=myfile.read()
submit(email, submission_token, key, part, [part], data)